# Generated by Django 2.2 on 2019-12-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('nai_jishu', models.FloatField()),
                ('nai_jiliang', models.FloatField()),
                ('gm_jishu', models.FloatField()),
                ('gm_jiliang', models.FloatField()),
                ('n_jishu', models.FloatField()),
                ('n_jiliang', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('alarm_status', models.CharField(max_length=10)),
            ],
        ),
    ]
